# Generated by Django 3.0.5 on 2020-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=40, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('1', 'Мужской'), ('2', 'Женский')], max_length=5, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('telephone', models.CharField(max_length=30, verbose_name='Номер контактного телефона')),
                ('type_education', models.CharField(choices=[('1', 'Отсутствует'), ('2', 'Среднее общее образование'), ('3', 'Среднее профессиональное образование'), ('4', 'Высшее образование')], max_length=5, verbose_name='Вид образования')),
                ('program', models.CharField(max_length=60, verbose_name='Направление')),
                ('qualification', models.CharField(max_length=60, verbose_name='Квалификация')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес проживания')),
                ('ready_to_move', models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], max_length=5, verbose_name='Готовность к переезду')),
                ('work_type', models.CharField(choices=[('1', 'Производство'), ('2', 'Экономика и финансы'), ('3', 'Общее управление'), ('4', 'Другое')], max_length=5, verbose_name='Направление деятельности')),
                ('work_post', models.CharField(max_length=60, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Анкеты соискателей',
                'verbose_name_plural': 'Анкеты соискателей',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=40, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('1', 'Мужской'), ('2', 'Женский')], max_length=5, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('telephone', models.CharField(max_length=30, verbose_name='Номер контактного телефона')),
                ('praktika', models.CharField(choices=[('1', 'Да'), ('2', 'Нет, только половину дня'), ('3', 'Другое')], max_length=5, verbose_name='Вы сможете проходить практику полный рабочий день?')),
                ('university', models.CharField(max_length=90, verbose_name='Наименование учебного заведения')),
                ('institute', models.CharField(max_length=60, verbose_name='Факультет')),
                ('specialty', models.CharField(max_length=60, verbose_name='Специальность')),
                ('year_of_begin', models.IntegerField(verbose_name='Год поступления')),
                ('year_of_end', models.IntegerField(verbose_name='Год окончания')),
            ],
            options={
                'verbose_name': 'Анкеты студентов',
                'verbose_name_plural': 'Анкеты студентов',
            },
        ),
    ]
