# Generated by Django 3.0.5 on 2020-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='upload',
            field=models.FileField(default=1, upload_to='upload/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
